/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker"

import { HttpResponse, delay, http } from "msw"

import { TypeEnum } from "../models/api"
import type {
    CreateDailyTodoOption,
    CreateInspirationOption,
    DailyTodoOption,
    DailyTodosModule,
    DefaultOKResponse,
    FileUpload,
    InspirationModule,
    InspirationOption,
    PaginatedDailyTodoOptionList,
    PaginatedDailyTodosModuleList,
    PaginatedInspirationModuleList,
    PaginatedInspirationOptionList,
    PaginatedUserList,
    User,
} from "../models/api"

export const getCsrfRetrieveResponseMock = (overrideResponse: Partial<DefaultOKResponse> = {}): DefaultOKResponse => ({
    status: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    ...overrideResponse,
})

export const getDailyTodoOptionsListResponseMock = (overrideResponse: Partial<PaginatedDailyTodoOptionList> = {}): PaginatedDailyTodoOptionList => ({
    pageCount: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        name: faker.string.alpha({ length: { min: 1, max: 30 } }),
        text: faker.string.alpha({ length: { min: 10, max: 20 } }),
    })),
    ...overrideResponse,
})

export const getDailyTodoOptionsCreateResponseMock = (overrideResponse: Partial<CreateDailyTodoOption> = {}): CreateDailyTodoOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 1, max: 30 } }),
    text: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getDailyTodoOptionsRetrieveResponseMock = (overrideResponse: Partial<DailyTodoOption> = {}): DailyTodoOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 1, max: 30 } }),
    text: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getDailyTodoOptionsUpdateResponseMock = (overrideResponse: Partial<DailyTodoOption> = {}): DailyTodoOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 1, max: 30 } }),
    text: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getDailyTodoOptionsPartialUpdateResponseMock = (overrideResponse: Partial<DailyTodoOption> = {}): DailyTodoOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 1, max: 30 } }),
    text: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getDailyTodosModulesListResponseMock = (overrideResponse: Partial<PaginatedDailyTodosModuleList> = {}): PaginatedDailyTodosModuleList => ({
    pageCount: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    })),
    ...overrideResponse,
})

export const getDailyTodosModulesCreateResponseMock = (overrideResponse: Partial<DailyTodosModule> = {}): DailyTodosModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getDailyTodosModulesRetrieveResponseMock = (overrideResponse: Partial<DailyTodosModule> = {}): DailyTodosModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getDailyTodosModulesUpdateResponseMock = (overrideResponse: Partial<DailyTodosModule> = {}): DailyTodosModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getDailyTodosModulesPartialUpdateResponseMock = (overrideResponse: Partial<DailyTodosModule> = {}): DailyTodosModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getFileUploadsCreateResponseMock = (overrideResponse: Partial<FileUpload> = {}): FileUpload => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    fileUUID: faker.string.uuid(),
    fileName: faker.helpers.fromRegExp('^[^<>:;,?"*|/]+$'),
    fileUploadURL: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationModulesListResponseMock = (overrideResponse: Partial<PaginatedInspirationModuleList> = {}): PaginatedInspirationModuleList => ({
    pageCount: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    })),
    ...overrideResponse,
})

export const getInspirationModulesCreateResponseMock = (overrideResponse: Partial<InspirationModule> = {}): InspirationModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationModulesRetrieveResponseMock = (overrideResponse: Partial<InspirationModule> = {}): InspirationModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationModulesUpdateResponseMock = (overrideResponse: Partial<InspirationModule> = {}): InspirationModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationModulesPartialUpdateResponseMock = (overrideResponse: Partial<InspirationModule> = {}): InspirationModule => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    user: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationOptionsListResponseMock = (overrideResponse: Partial<PaginatedInspirationOptionList> = {}): PaginatedInspirationOptionList => ({
    pageCount: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        type: faker.helpers.arrayElement(Object.values(TypeEnum)),
        text: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
        image: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }), undefined]),
        imageURL: faker.string.alpha({ length: { min: 10, max: 20 } }),
    })),
    ...overrideResponse,
})

export const getInspirationOptionsCreateResponseMock = (overrideResponse: Partial<CreateInspirationOption> = {}): CreateInspirationOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.helpers.arrayElement(Object.values(TypeEnum)),
    text: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    image: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }), undefined]),
    imageURL: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationOptionsRetrieveResponseMock = (overrideResponse: Partial<InspirationOption> = {}): InspirationOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.helpers.arrayElement(Object.values(TypeEnum)),
    text: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    image: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }), undefined]),
    imageURL: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationOptionsUpdateResponseMock = (overrideResponse: Partial<InspirationOption> = {}): InspirationOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.helpers.arrayElement(Object.values(TypeEnum)),
    text: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    image: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }), undefined]),
    imageURL: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getInspirationOptionsPartialUpdateResponseMock = (overrideResponse: Partial<InspirationOption> = {}): InspirationOption => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    module: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.helpers.arrayElement(Object.values(TypeEnum)),
    text: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    image: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }), undefined]),
    imageURL: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getUsersListResponseMock = (overrideResponse: Partial<PaginatedUserList> = {}): PaginatedUserList => ({
    pageCount: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    results: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        url: faker.internet.url(),
        username: faker.helpers.fromRegExp("^[\w.@+-]+$"),
        email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
        is_staff: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    })),
    ...overrideResponse,
})

export const getUsersCreateResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    url: faker.internet.url(),
    username: faker.helpers.fromRegExp("^[\w.@+-]+$"),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    is_staff: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
})

export const getUsersRetrieveResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    url: faker.internet.url(),
    username: faker.helpers.fromRegExp("^[\w.@+-]+$"),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    is_staff: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
})

export const getUsersUpdateResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    url: faker.internet.url(),
    username: faker.helpers.fromRegExp("^[\w.@+-]+$"),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    is_staff: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
})

export const getUsersPartialUpdateResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    url: faker.internet.url(),
    username: faker.helpers.fromRegExp("^[\w.@+-]+$"),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    is_staff: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
})

export const getCsrfRetrieveMockHandler = (overrideResponse?: DefaultOKResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DefaultOKResponse> | DefaultOKResponse)) => {
    return http.get("*/api/v1/csrf/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getCsrfRetrieveResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodoOptionsListMockHandler = (
    overrideResponse?: PaginatedDailyTodoOptionList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedDailyTodoOptionList> | PaginatedDailyTodoOptionList)
) => {
    return http.get("*/api/v1/daily-todo-options/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodoOptionsListResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodoOptionsCreateMockHandler = (
    overrideResponse?: CreateDailyTodoOption | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateDailyTodoOption> | CreateDailyTodoOption)
) => {
    return http.post("*/api/v1/daily-todo-options/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodoOptionsCreateResponseMock()),
            { status: 201, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodoOptionsRetrieveMockHandler = (overrideResponse?: DailyTodoOption | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DailyTodoOption> | DailyTodoOption)) => {
    return http.get("*/api/v1/daily-todo-options/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodoOptionsRetrieveResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodoOptionsUpdateMockHandler = (overrideResponse?: DailyTodoOption | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<DailyTodoOption> | DailyTodoOption)) => {
    return http.put("*/api/v1/daily-todo-options/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodoOptionsUpdateResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodoOptionsPartialUpdateMockHandler = (
    overrideResponse?: DailyTodoOption | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<DailyTodoOption> | DailyTodoOption)
) => {
    return http.patch("*/api/v1/daily-todo-options/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(
                overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodoOptionsPartialUpdateResponseMock()
            ),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodoOptionsDestroyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
    return http.delete("*/api/v1/daily-todo-options/:id/", async (info) => {
        await delay(1000)
        if (typeof overrideResponse === "function") {
            await overrideResponse(info)
        }
        return new HttpResponse(null, { status: 204 })
    })
}

export const getDailyTodosModulesListMockHandler = (
    overrideResponse?: PaginatedDailyTodosModuleList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedDailyTodosModuleList> | PaginatedDailyTodosModuleList)
) => {
    return http.get("*/api/v1/daily-todos-modules/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodosModulesListResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodosModulesCreateMockHandler = (
    overrideResponse?: DailyTodosModule | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DailyTodosModule> | DailyTodosModule)
) => {
    return http.post("*/api/v1/daily-todos-modules/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodosModulesCreateResponseMock()),
            { status: 201, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodosModulesRetrieveMockHandler = (
    overrideResponse?: DailyTodosModule | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DailyTodosModule> | DailyTodosModule)
) => {
    return http.get("*/api/v1/daily-todos-modules/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodosModulesRetrieveResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodosModulesUpdateMockHandler = (
    overrideResponse?: DailyTodosModule | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<DailyTodosModule> | DailyTodosModule)
) => {
    return http.put("*/api/v1/daily-todos-modules/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodosModulesUpdateResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodosModulesPartialUpdateMockHandler = (
    overrideResponse?: DailyTodosModule | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<DailyTodosModule> | DailyTodosModule)
) => {
    return http.patch("*/api/v1/daily-todos-modules/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(
                overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getDailyTodosModulesPartialUpdateResponseMock()
            ),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getDailyTodosModulesDestroyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
    return http.delete("*/api/v1/daily-todos-modules/:id/", async (info) => {
        await delay(1000)
        if (typeof overrideResponse === "function") {
            await overrideResponse(info)
        }
        return new HttpResponse(null, { status: 204 })
    })
}

export const getFileUploadsCreateMockHandler = (overrideResponse?: FileUpload | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<FileUpload> | FileUpload)) => {
    return http.post("*/api/v1/file-uploads/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getFileUploadsCreateResponseMock()),
            { status: 201, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationModulesListMockHandler = (
    overrideResponse?: PaginatedInspirationModuleList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedInspirationModuleList> | PaginatedInspirationModuleList)
) => {
    return http.get("*/api/v1/inspiration-modules/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationModulesListResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationModulesCreateMockHandler = (
    overrideResponse?: InspirationModule | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<InspirationModule> | InspirationModule)
) => {
    return http.post("*/api/v1/inspiration-modules/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationModulesCreateResponseMock()),
            { status: 201, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationModulesRetrieveMockHandler = (
    overrideResponse?: InspirationModule | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InspirationModule> | InspirationModule)
) => {
    return http.get("*/api/v1/inspiration-modules/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationModulesRetrieveResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationModulesUpdateMockHandler = (
    overrideResponse?: InspirationModule | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<InspirationModule> | InspirationModule)
) => {
    return http.put("*/api/v1/inspiration-modules/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationModulesUpdateResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationModulesPartialUpdateMockHandler = (
    overrideResponse?: InspirationModule | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<InspirationModule> | InspirationModule)
) => {
    return http.patch("*/api/v1/inspiration-modules/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(
                overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationModulesPartialUpdateResponseMock()
            ),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationModulesDestroyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
    return http.delete("*/api/v1/inspiration-modules/:id/", async (info) => {
        await delay(1000)
        if (typeof overrideResponse === "function") {
            await overrideResponse(info)
        }
        return new HttpResponse(null, { status: 204 })
    })
}

export const getInspirationOptionsListMockHandler = (
    overrideResponse?: PaginatedInspirationOptionList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedInspirationOptionList> | PaginatedInspirationOptionList)
) => {
    return http.get("*/api/v1/inspiration-options/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationOptionsListResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationOptionsCreateMockHandler = (
    overrideResponse?: CreateInspirationOption | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateInspirationOption> | CreateInspirationOption)
) => {
    return http.post("*/api/v1/inspiration-options/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationOptionsCreateResponseMock()),
            { status: 201, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationOptionsRetrieveMockHandler = (
    overrideResponse?: InspirationOption | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InspirationOption> | InspirationOption)
) => {
    return http.get("*/api/v1/inspiration-options/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationOptionsRetrieveResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationOptionsUpdateMockHandler = (
    overrideResponse?: InspirationOption | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<InspirationOption> | InspirationOption)
) => {
    return http.put("*/api/v1/inspiration-options/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationOptionsUpdateResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationOptionsPartialUpdateMockHandler = (
    overrideResponse?: InspirationOption | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<InspirationOption> | InspirationOption)
) => {
    return http.patch("*/api/v1/inspiration-options/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(
                overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getInspirationOptionsPartialUpdateResponseMock()
            ),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getInspirationOptionsDestroyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
    return http.delete("*/api/v1/inspiration-options/:id/", async (info) => {
        await delay(1000)
        if (typeof overrideResponse === "function") {
            await overrideResponse(info)
        }
        return new HttpResponse(null, { status: 204 })
    })
}

export const getUsersListMockHandler = (overrideResponse?: PaginatedUserList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedUserList> | PaginatedUserList)) => {
    return http.get("*/api/v1/users/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getUsersListResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getUsersCreateMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<User> | User)) => {
    return http.post("*/api/v1/users/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getUsersCreateResponseMock()),
            { status: 201, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getUsersRetrieveMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User)) => {
    return http.get("*/api/v1/users/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getUsersRetrieveResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getUsersUpdateMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<User> | User)) => {
    return http.put("*/api/v1/users/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getUsersUpdateResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getUsersPartialUpdateMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<User> | User)) => {
    return http.patch("*/api/v1/users/:id/", async (info) => {
        await delay(1000)

        return new HttpResponse(
            JSON.stringify(overrideResponse !== undefined ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) : getUsersPartialUpdateResponseMock()),
            { status: 200, headers: { "Content-Type": "application/json" } }
        )
    })
}

export const getUsersDestroyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
    return http.delete("*/api/v1/users/:id/", async (info) => {
        await delay(1000)
        if (typeof overrideResponse === "function") {
            await overrideResponse(info)
        }
        return new HttpResponse(null, { status: 204 })
    })
}
export const getWijckieAPIMock = () => [
    getCsrfRetrieveMockHandler(),
    getDailyTodoOptionsListMockHandler(),
    getDailyTodoOptionsCreateMockHandler(),
    getDailyTodoOptionsRetrieveMockHandler(),
    getDailyTodoOptionsUpdateMockHandler(),
    getDailyTodoOptionsPartialUpdateMockHandler(),
    getDailyTodoOptionsDestroyMockHandler(),
    getDailyTodosModulesListMockHandler(),
    getDailyTodosModulesCreateMockHandler(),
    getDailyTodosModulesRetrieveMockHandler(),
    getDailyTodosModulesUpdateMockHandler(),
    getDailyTodosModulesPartialUpdateMockHandler(),
    getDailyTodosModulesDestroyMockHandler(),
    getFileUploadsCreateMockHandler(),
    getInspirationModulesListMockHandler(),
    getInspirationModulesCreateMockHandler(),
    getInspirationModulesRetrieveMockHandler(),
    getInspirationModulesUpdateMockHandler(),
    getInspirationModulesPartialUpdateMockHandler(),
    getInspirationModulesDestroyMockHandler(),
    getInspirationOptionsListMockHandler(),
    getInspirationOptionsCreateMockHandler(),
    getInspirationOptionsRetrieveMockHandler(),
    getInspirationOptionsUpdateMockHandler(),
    getInspirationOptionsPartialUpdateMockHandler(),
    getInspirationOptionsDestroyMockHandler(),
    getUsersListMockHandler(),
    getUsersCreateMockHandler(),
    getUsersRetrieveMockHandler(),
    getUsersUpdateMockHandler(),
    getUsersPartialUpdateMockHandler(),
    getUsersDestroyMockHandler(),
]
