# Generated by Django 5.2.1 on 2025-08-01 06:11

import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("nl", "Nl"), ("en-GB", "En Gb")],
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        choices=[
                            ("Europe/Amsterdam", "Europe Amsterdam"),
                            ("Europe/London", "Europe London"),
                        ],
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
