# Generated by Django 5.2.1 on 2025-08-21 13:51

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wijckie_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("file_uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "file_name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "expected_reference",
                    models.CharField(
                        choices=[
                            ("InspirationOption_image", "Inspiration Option Image")
                        ],
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["file_uuid"], name="wijckie_mod_file_uu_584391_idx"
                    ),
                    models.Index(
                        fields=["expected_reference"],
                        name="wijckie_mod_expecte_e09b82_idx",
                    ),
                ],
            },
        ),
    ]
