# Generated by Django 5.2.1 on 2025-08-12 08:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wijckie_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspirationModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="InspirationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "type",
                    models.TextField(choices=[("text", "Text"), ("image", "Image")]),
                ),
                ("text", models.TextField(null=True)),
                ("image", models.FileField(null=True, upload_to="inspiration")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.inspirationmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "type", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="InspirationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.inspirationmodule",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.inspirationoption",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "date", "option", "id"],
            },
        ),
        migrations.CreateModel(
            name="InspirationWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.inspirationmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="inspirationoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "text"), _negated=True),
                    ("text__isnull", False),
                    _connector="OR",
                ),
                name="inspiration_option__text",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspirationoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "image"), _negated=True),
                    ("image__isnull", False),
                    _connector="OR",
                ),
                name="inspiration_option__image",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inspirationitem",
            unique_together={("module", "date")},
        ),
    ]
