# Generated by Django 5.2.1 on 2025-09-02 14:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wijckie_models", "0003_inspiration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTodosModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DailyTodoOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("text", models.TextField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.dailytodosmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DailyTodoWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.dailytodosmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DailyTodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("todo", "Todo"), ("skip", "Skip"), ("done", "Done")],
                        max_length=30,
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.dailytodooption",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wijckie_models.dailytodosmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "date", "option", "id"],
                "unique_together": {("module", "date")},
            },
        ),
    ]
