# Generated by Django 5.2.1 on 2025-09-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wijckie_models", "0004_dailytodos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DailyTodoWidget",
            new_name="DailyTodosWidget",
        ),
    ]
