# Generated by Django 5.2.1 on 2025-09-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wijckie_models", "0005_rename_dailytodowidget"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailytodoitem",
            unique_together={("module", "date", "option")},
        ),
    ]
