# Generated by Django 5.2.1 on 2025-11-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wijckie_models", "0006_alter_dailytodoitem_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailytodosmodule",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="inspirationmodule",
            options={"ordering": ["-created_at"]},
        ),
    ]
