/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */

export type DailyTodoOptionsListParams = {
    module?: number
    /**
     * A page number within the paginated result set.
     */
    page?: number
}
