/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default back-end API for Wijckie.io
 * OpenAPI spec version: 1.0.0
 */

export interface DefaultOKResponse {
  status?: string;
}
