/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */

export interface FileUpload {
    readonly id: number
    readonly user: number
    readonly createdAt: string
    readonly fileUUID: string
    fileName: string
    readonly fileUploadURL: string
}
