/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */

export * from "./createInspirationOption"
export * from "./defaultOKResponse"
export * from "./fileUpload"
export * from "./imageUploadRequest"
export * from "./imageUploadResponse"
export * from "./inspirationModule"
export * from "./inspirationModulesListParams"
export * from "./inspirationOption"
export * from "./inspirationOptionUpload"
export * from "./inspirationOptionsListParams"
export * from "./paginatedInspirationModuleList"
export * from "./paginatedInspirationOptionList"
export * from "./paginatedUserList"
export * from "./patchedInspirationModule"
export * from "./patchedInspirationOption"
export * from "./patchedUser"
export * from "./typeEnum"
export * from "./user"
export * from "./userCreation"
export * from "./usersListParams"
