/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */

export * from "./defaultOKResponse"
export * from "./inspirationModule"
export * from "./inspirationModulesListParams"
export * from "./paginatedInspirationModuleList"
export * from "./paginatedUserList"
export * from "./patchedInspirationModule"
export * from "./patchedUser"
export * from "./user"
export * from "./userCreation"
export * from "./usersListParams"
