/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */

export interface InspirationItem {
    readonly id: number
    readonly module: number
    readonly date: string
    readonly option: number
}
