/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */
import type { DailyTodosModule } from "./dailyTodosModule"

export interface PaginatedDailyTodosModuleList {
    pageCount: number
    results: DailyTodosModule[]
}
