/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */
import type { DailyTodosWidget } from "./dailyTodosWidget"

export interface PaginatedDailyTodosWidgetList {
    pageCount: number
    results: DailyTodosWidget[]
}
