/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user"

export interface PaginatedUserList {
    pageCount: number
    results: User[]
}
