/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */
import type { InspirationOption } from "./inspirationOption"

export interface PaginatedInspirationOptionList {
    pageCount: number
    results: InspirationOption[]
}
