/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */
import type { InspirationModule } from "./inspirationModule"

export interface PaginatedInspirationModuleList {
    pageCount: number
    results: InspirationModule[]
}
