/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */
import type { InspirationWidget } from "./inspirationWidget"

export interface PaginatedInspirationWidgetList {
    pageCount: number
    results: InspirationWidget[]
}
