/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default back-end API for Wijckie.io
 * OpenAPI spec version: 1.0.0
 */

export interface UserCreation {
    readonly url: string
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @maxLength 150
     * @pattern ^[\w.@+-]+$
     */
    username: string
    /** @maxLength 254 */
    email?: string
    /** Designates whether the user can log into this admin site. */
    is_staff?: boolean
}
