/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Wijckie API
 * Default API for Wijckie
 * OpenAPI spec version: 1.0.0
 */

export interface User {
    readonly url: string
    /**
     * @maxLength 50
     * @pattern ^[\w.@+-]+$
     */
    username: string
    /** @maxLength 254 */
    email?: string
    is_staff?: boolean
}
